"""'Post增加新的字段'

Revision ID: 08d8ea97f782
Revises: 30f4fe8906f3
Create Date: 2021-06-04 17:07:35.585637

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08d8ea97f782'
down_revision = '30f4fe8906f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', mysql.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
