"""'Post增加新的字段'

Revision ID: 30f4fe8906f3
Revises: 93403f0f5390
Create Date: 2021-06-04 17:06:30.177099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30f4fe8906f3'
down_revision = '93403f0f5390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('test', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    op.drop_column('post', 'title')
    # ### end Alembic commands ###
