"""new post

Revision ID: 3e16c4d83239
Revises: 03e8a497ae05
Create Date: 2021-06-18 10:52:17.199556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e16c4d83239'
down_revision = '03e8a497ae05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('post', sa.Column('reply', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'reply')
    op.drop_column('post', 'count')
    # ### end Alembic commands ###
